import type { CharacterCard, BeltColor, DailyPuzzle, Achievement } from '../types';

export const BELT_LEVELS: { belt: BeltColor; minXp: number; title: string; colorClass: string }[] = [
  { belt: 'White',  minXp: 0,    title: 'Novice Disciple',  colorClass: 'bg-slate-200 text-slate-800' },
  { belt: 'Yellow', minXp: 100,  title: 'Temple Initiate',  colorClass: 'bg-yellow-400 text-yellow-900' },
  { belt: 'Orange', minXp: 300,  title: 'Bamboo Striker',   colorClass: 'bg-orange-500 text-white' },
  { belt: 'Green',  minXp: 600,  title: 'Jade Defender',    colorClass: 'bg-emerald-600 text-white' },
  { belt: 'Blue',   minXp: 1000, title: 'Flowing Crane',    colorClass: 'bg-blue-600 text-white' },
  { belt: 'Brown',  minXp: 1500, title: 'Earth Tiger',      colorClass: 'bg-amber-800 text-white' },
  { belt: 'Black',  minXp: 2500, title: 'Dragon Master',    colorClass: 'bg-slate-900 text-amber-400 border border-amber-400' },
];

export const CHARACTER_CARDS: CharacterCard[] = [
  {
    id: 'po_common',
    name: 'Po (Initiate)',
    rarity: 'common',
    image: '/assets/card_pack/po_common.png',
    stars: 1,
    bonuses: ['+10% Score bonus on Common Words', '+10 XP per Puzzle Completed', '+2 Streak Shield Tokens'],
    description: 'A passionate panda who dreams of kung fu greatness. Slow but full of determination.',
  },
  {
    id: 'monkey_common',
    name: 'Master Monkey',
    rarity: 'common',
    image: '/assets/card_pack/monkey_common.png',
    stars: 1,
    bonuses: ['+10Submission Speed Bonus', '+5 Coins on 4-Letter Words', '+2 Streak Shield Tokens'],
    description: 'Playful, mischievous, and incredibly agile. Monkey uses speed and trickery to confuse foes.',
  },
  {
    id: 'crane_common',
    name: 'Master Crane',
    rarity: 'common',
    image: '/assets/card_pack/crane_common.png',
    stars: 1,
    bonuses: ['Hover Ability: Shuffles are free', '+10 XP on Easy Puzzles', '+2 Streak Shield Tokens'],
    description: 'Calm and steady. Crane utilizes defensive maneuvers to redirect enemy force with grace.',
  },
  {
    id: 'mantis_rare',
    name: 'Master Mantis',
    rarity: 'rare',
    image: '/assets/card_pack/mantis_rare.png',
    stars: 3,
    bonuses: ['Pinpoint Strike: Double points for 5-letter words', '+20 XP per Puzzle Completed'],
    description: 'Small but mighty. Mantis strikes with absolute precision and blinding speed.',
  },
  {
    id: 'viper_rare',
    name: 'Master Viper',
    rarity: 'rare',
    image: '/assets/card_pack/viper_rare.png',
    stars: 3,
    bonuses: ['Coiled Defense: Retain streak on first invalid word', '+10 Coins per Puzzle Completed'],
    description: 'A compassionate dancer who fights with flexible and unpredictable strikes.',
  },
  {
    id: 'tigress_rare',
    name: 'Master Tigress',
    rarity: 'rare',
    image: '/assets/card_pack/tigress_rare.png',
    stars: 3,
    bonuses: ['Tiger Claw: Double points for words starting with Center Letter', '+15% Score Overall'],
    description: 'The strongest and most dedicated of the Furious Five. Fierce, disciplined, and powerful.',
  },
  {
    id: 'shifu_epic',
    name: 'Master Shifu',
    rarity: 'epic',
    image: '/assets/card_pack/shifu_epic.png',
    stars: 4,
    bonuses: ['Inner Peace: Double streak score multipliers', '+25% Coins from all sources'],
    description: 'The wise master of the Jade Palace. Patiently guides others to unlock their inner potential.',
  },
  {
    id: 'dragon_warrior_po',
    name: 'Dragon Warrior Po',
    rarity: 'epic',
    image: '/assets/card_pack/dragon_warrior_po_epic.png',
    stars: 4,
    bonuses: ['Wuxi Finger Hold: Auto-reveal 1 word per puzzle', '+35% XP Overall', '+20% Score Overall'],
    description: 'The legendary Dragon Warrior. Combines body weight, noodle-eating stamina, and inner peace.',
  },
  {
    id: 'oogway_legendary',
    name: 'Grand Master Oogway',
    rarity: 'legendary',
    image: '/assets/card_pack/oogway_legendary.png',
    stars: 5,
    bonuses: [
      'Universal Harmony: Free word suggestions',
      'Double XP & Coins from all puzzles',
      'Instantly clear letter wheel once per puzzle for a massive score multiplier',
    ],
    description: 'The founder of Kung Fu and the Valley of Peace. His wisdom is infinite and his moves are timeless.',
  },
];

export const DAILY_PUZZLES: DailyPuzzle[] = [
  {
    id: 'puzzle_1',
    letters: ['A', 'D', 'N', 'P', 'S', 'T', 'G'],
    centerLetter: 'A',
    validWords: [
      'PANDA','PANDAS','SAND','SPAN','SNAP','PAST','SPAT','TAPS',
      'PANS','PATS','NAPS','STAND','SAT','AND','TAG','TAGS',
      'GASP','GAP','GAPS','PANG','PANGS','PAGAN','PAGANS',
    ],
    difficulty: 'Easy',
    xpReward: 50,
    coinReward: 25,
  },
  {
    id: 'puzzle_2',
    letters: ['D', 'R', 'A', 'G', 'O', 'N', 'S'],
    centerLetter: 'O',
    validWords: [
      'DRAGON','DRAGONS','ROAD','ROADS','ORGAN','ORGANS','SONG',
      'SONGS','SOAR','GROAN','GROANS','DONOR','DONORS','GOAD','GOADS','RADON',
    ],
    difficulty: 'Medium',
    xpReward: 100,
    coinReward: 50,
  },
  {
    id: 'puzzle_3',
    letters: ['E', 'M', 'A', 'S', 'T', 'R', 'C'],
    centerLetter: 'E',
    validWords: [
      'MASTER','MASTERS','STEAM','TEAMS','SEAM','MEAT','TAME',
      'CRATE','CRATES','CREAM','CREAMS','SCREAM','SCREAMS','ACRE',
      'ACRES','TEAR','TEARS','STARE','RATES','MATE','MATES',
    ],
    difficulty: 'Hard',
    xpReward: 200,
    coinReward: 100,
  },
];

export const DEFAULT_ACHIEVEMENTS: Achievement[] = [
  {
    id: 'first_word',
    title: 'First Strike',
    description: 'Find your first correct word in any puzzle.',
    unlocked: false,
    progress: 0,
    target: 1,
    rewardXp: 10,
    rewardCoins: 5,
    iconName: 'Zap',
  },
  {
    id: 'puzzle_master',
    title: 'Scroll Guardian',
    description: 'Complete 3 full puzzles.',
    unlocked: false,
    progress: 0,
    target: 3,
    rewardXp: 100,
    rewardCoins: 50,
    iconName: 'Scroll',
  },
  {
    id: 'collector',
    title: 'Furious Collection',
    description: 'Unlock 5 different character cards.',
    unlocked: false,
    progress: 1,
    target: 5,
    rewardXp: 150,
    rewardCoins: 75,
    iconName: 'Sparkles',
  },
  {
    id: 'streak_warrior',
    title: 'Unstoppable Flow',
    description: 'Build a word streak of 5 in a single puzzle.',
    unlocked: false,
    progress: 0,
    target: 5,
    rewardXp: 50,
    rewardCoins: 25,
    iconName: 'Flame',
  },
  {
    id: 'gold_belter',
    title: 'Jade Master',
    description: 'Reach the Green Belt rank.',
    unlocked: false,
    progress: 0,
    target: 600,
    rewardXp: 200,
    rewardCoins: 100,
    iconName: 'Shield',
  },
];
